### ISSUE TITLE
after update to 3.7.0: unsupported attribute "mirrormaker_user_config"

### ISSUE THREAD

**Issue by mkhl** [aiven/terraform-provider-aiven#927] opened 2022-10-11 07:10 UTC
## What happened?

we have a kafka/prometheus integration that we created with v1 of the aiven provider; later we upgraded the provider to v2 and then v3.6 (and terraform from 0.12 all the way to 1.2)

trying to update to v3.7.0 now the provider fails with this error message:

```
╷
│ Error: Failed to decode resource from state
│ 
│ Error decoding "aiven_service_integration.kafka_prometheus" from previous
│ state: unsupported attribute "mirrormaker_user_config"
╵
```

## What did you expect to happen?

the provider works and shows that no changes are planned :)

## What else do we need to know?

as far as i know we were never using mirrormaker so i guess this would be some default value that ended up in the remote state and never got cleaned up?

**Comment by byashimov** [comment] 2022-10-12 10:31
Hi! Could you check out your terraform.tfstate file for the "mirrormaker_user_config" field?  
If it's there try to drop it, and the please run "plan" again.
Please be careful and don't apply things if not sure it's safe. Thanks.

**Comment by mkhl** [comment] 2022-10-12 12:53
well if i do that the provider still crashes because of #914/#909 :upside_down_face: 

but: i noticed that applying a plan with the 3.6.0 version creates a state without the `mirrormaker_user_config` field
**but** using the settings web ui (as i mentioned in #909) creates a state where the field is back and the provider crashes again

**Comment by Serpentiel** [comment] 2022-10-17 07:57
hey, thank you for reporting this!

`mirrormaker_user_config` is no longer reported by the API as a supported field

I will check this with the relevant team, as it might be a backend issue, especially taking in the account the fact that the issue is only reproducible via web UI

**Comment by Serpentiel** [comment] 2022-10-17 12:05
hey again, @mkhl

could you please point out which settings to change in the web UI to trigger this behavior?

**Comment by mkhl** [comment] 2022-10-17 12:08
i think for this i also added an IP address but i can double-check tomorrow

**Comment by Serpentiel** [comment] 2022-10-17 12:08
I will check this for you now and will get back if this is reproducible in a more reliable way :)

**Comment by Serpentiel** [comment] 2022-10-17 13:04
hey, getting back to you about this matter:

I was only able to reproduce the crash described in #909, however I was unable to make it to add the removed `mirrormaker_user_config` to the state by adding allowed IPs via web UI

however, as I mentioned above, the issue with `mirrormaker_user_config` has been resolved, and will be rolled out soon with the upcoming release of Aiven Provider for Terraform

please keep in mind that the `mirrormaker_user_config` option will be removed in any upcoming major release of the provider, however additional migration instructions and/or relevant migration helper scripts will be released when this occurs

I will close this as this has been resolved

in case of an urgency, feel free to use [5e5cb8f](https://github.com/aiven/terraform-provider-aiven/commit/5e5cb8ff1ab9ff155243860045de853f4e85d406) and manually build it, otherwise you're welcome to wait for the upcoming release!

thank you again for reporting this!

**Closed by Serpentiel** 2022-10-17 13:04 UTC
Labels: bug, customer request
