### ISSUE TITLE
Creating azure privatelink for rebalancing service hangs

### ISSUE THREAD

**Issue by gandelman-a** [aiven/terraform-provider-aiven#680] opened 2022-02-08 20:07 UTC
Running into problems upgrading _existing_ infra with the newly added static IPs and `aiven_azure_privatelink`functionality.

* postgresl service deployed previously _without_ static IPs associated.
* tf plan/apply which
  * creates and associates static IPs to the existing service
  * creates an `aiven_azure_privatelink` associated to said service

Proper dependencies are in-place between the `aiven_pg` and `aiven_azure_privatelink` resources.

Modification of the `aiven_pg` service completes.  Actual service enters into a rebalancing state asynchronously in the background.  

The `aiven_azure_privatelink` proceeds to create but never completes, even after the associated service completes its rebalance.

Manually removing the azure privatelink from the service, waiting for it to delete, and re-running terraform successfully creates it.

Not sure this is expected or a bug on the server side. I'd expect the privatelink to _eventually_ complete after rebalancing. If its the case that this needs to be phased across 2 terraform runs (phase1: associate static IPs + rebalance, phase2: create privatelink), then we shoudl call it out somewhere in provider docs.

**Comment by mhoffm-aiven** [comment] 2022-02-09 07:03
Should in principle finish in one apply. Do you have an reproducing example?

**Comment by mhoffm-aiven** [comment] 2022-02-09 15:01
Ok after talking to the team, this seems to be API related and has to be fixed in the backend. The mitigation for now is to apply updates in 2 phases like you described, but let me quote here for reference:

> Not sure this is expected or a bug on the server side. I'd expect the privatelink to eventually complete after rebalancing. If its the case that this needs to be phased across 2 terraform runs (phase1: associate static IPs + rebalance, phase2: create privatelink), then we shoudl call it out somewhere in provider docs.

This is a race condition that is more likely to occur with TF and only present for azure privatelink. We will create an internal issue to track this problem and link it to your support conversation so you can receive updates as and when they happen.

**Comment by mhoffm-aiven** [comment] 2022-07-05 10:55
Hey @gandelman-a , 

sorry i forgot to ping, this issue has been closed in the backend for a while now! I'll close this issue now; if you still experience this error please consider it a bug and reopen this ticket!

Thanks

**Closed by mhoffm-aiven** 2022-07-05 10:55 UTC
