### ISSUE TITLE
Change to aiven_mirrormaker_replication_flow resource affects unspecified optional fields

### ISSUE THREAD

**Issue by nickgooding** [aiven/terraform-provider-aiven#1632] opened 2024-03-05 14:47 UTC
## What happened?

Updating attribute(s) for a `aiven_mirrormaker_replication_flow` resource appears to be able to affect unrelated configuration.

Example:
1. Given the following resource:
```hcl
resource "aiven_mirrormaker_replication_flow" "this" {
  project        = "example-project"
  service_name   = "mirrormaker"
  source_cluster = "source-cluster"
  target_cluster = "target-cluster"
  enable         = true

  topics = [
    "example-topic",
  ]
}
```

Aiven Console view before:
![Screenshot from 2024-03-05 14-33-58](https://github.com/aiven/terraform-provider-aiven/assets/73336146/d63665c4-648c-48cd-9e35-3d79c5e39d9b)

2. Make the following change and re-apply
```diff
--- a/main.tf
+++ b/main.tf
@@ -7,6 +7,6 @@ resource "aiven_mirrormaker_replication_flow" "this" {
 
   topics = [
    "example-topic",
+   "another-topic",
   ]
 }
```

Plan:
```
$ terraform apply
aiven_mirrormaker_replication_flow.this: Refreshing state... [id=example-project/mirrormaker/source-cluster/target-cluster]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aiven_mirrormaker_replication_flow.this will be updated in-place
  ~ resource "aiven_mirrormaker_replication_flow" "this" {
        id                                  = "example-project/mirrormaker/source-cluster/target-cluster"
      ~ topics                              = [
            "example-topic",
          + "another-topic",
        ]
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aiven_mirrormaker_replication_flow.this: Modifying... [id=example-project/mirrormaker/source-cluster/target-cluster]
aiven_mirrormaker_replication_flow.this: Modifications complete after 1s [id=example-project/mirrormaker/source-cluster/target-cluster]
```

Aiven Console view after:
![Screenshot from 2024-03-05 14-34-29](https://github.com/aiven/terraform-provider-aiven/assets/73336146/77db3a72-c83a-49c6-a13f-5983d78c5f97)

Note that "Offset syncs topic location" has changed from "target" to "source" and "Emit heartbeats enabled" has toggled, despite neither being present in the resource or plan.

~~I haven't been able to reproduce this issue if `offset_syncs_topic_location` and `emit_heartbeats_enabled` are explicitly set for the resource.~~
Edit: I haven't been able to reproduce the issue for `offset_syncs_topic_location` if it is explicitly set for the resource. Unfortunately I've learned the hard way `emit_heartbeats_enabled` can switch itself back on.

## What did you expect to happen?

`another-topic` is added to the replication flow topic config and no other changes are made

## What else do we need to know?

Using v4.14.0 of the provider.

**Comment by nickgooding** [comment] 2024-03-05 14:55
Another possibly related issue: it does not appear to be possible to create a `aiven_mirrormaker_replication_flow` with `emit_heartbeats_enabled` set to false.

Plan:
```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aiven_mirrormaker_replication_flow.this will be created
  + resource "aiven_mirrormaker_replication_flow" "this" {
      + emit_backward_heartbeats_enabled    = false
      + emit_heartbeats_enabled             = false
      + enable                              = true
      + id                                  = (known after apply)
      + project                             = "example-project"
      + replication_policy_class            = "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
      + service_name                        = "mirrormaker"
      + source_cluster                      = "source-cluster"
      + sync_group_offsets_enabled          = false
      + sync_group_offsets_interval_seconds = 1
      + target_cluster                      = "target-cluster"
      + topics                              = [
          + "example-topic",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aiven_mirrormaker_replication_flow.this: Creating...
aiven_mirrormaker_replication_flow.this: Creation complete after 1s [id=example-project/mirrormaker/source-cluster/target-cluster]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
API response:
```
{
    "replication_flows": [
        {
            "enabled": true,
            "replication_policy_class": "org.apache.kafka.connect.mirror.DefaultReplicationPolicy",
            "source_cluster": "source-cluster",
            "sync_group_offsets_interval_seconds": 1,
            "target_cluster": "target-cluster",
            "topics": [
                "example-topic"
            ]
        }
    ]
}
```
(emit_heartbeats_enabled is not present)

Aiven console view:
![Screenshot from 2024-03-05 14-53-45](https://github.com/aiven/terraform-provider-aiven/assets/73336146/885098d1-d014-4f1c-9baa-a5965d737be1)

It's hard to know how to interpret the missing field in the API response and in the console it could just be a UI bug, but it appears that this does result in the enabling of heartbeats

**Comment by Serpentiel** [comment] 2024-03-14 20:12
Hey, @nickgooding! 👋

I've identified additional problematic fields, besides `emit_heartbeats_enabled`, and prepared a fix for them:

- `sync_group_offsets_enabled`
- `sync_group_offsets_interval_seconds`
- `emit_backward_heartbeats_enabled`

`offset_syncs_topic_location` is a different story. There is a problem with it being an optional field instead of being a required one, but it's actually quite interesting why the change happens.

Do I understand correctly that you also use Aiven Console or some other tool to manage the resource? I would like to remind you that when using IaaC tools such as Terraform, it's important to manage the state of the resource from a single "source of truth", i.e. nothing else should be used to manage the same resource besides the IaaC tool that you're using.

IaaC tools are designed in a way that makes them override the state of the resource if it's different from what the tool expects it to be, here's what exactly happens to the field in question:

- The field `offset_syncs_topic_location` is incorrectly defined in Terraform as an optional field, when in reality it should have either `source` or `target` as its value, i.e. it should be a required field
- You set `offset_syncs_topic_location` to `target` via Aiven Console or some other tool
- Terraform has an understanding that the field wasn't set at all, because it's optional, thus ignores it when forging a request to our API
  - It's important to understand that if, for example, the field was defined in Terraform and it changed externally, Terraform would then signalize about it, but since the field was never set in first place, Terraform can't know which value was there before, and therefore is unable to signalize about the external change
- Now, when Terraform tries to build the API request, it removes `offset_syncs_topic_location` completely from it, because when optional fields are unset, their presence in the API request is optional as well.
  - Normally, this shouldn't break things. But with this specific field (and, actually, with `replication_policy_class` too), when backend sees that the field is not present in the request, it resets those fields to a default value for the field, i.e:
    - `offset_syncs_topic_location` gets changed to `source`
    - `replication_policy_class` gets changed to `org.apache.kafka.connect.mirror.DefaultReplicationPolicy`

While this problem has occurred because the field was incorrectly defined as an optional one, we still recommend not to modify the state of any resource when using any IaaC solution. This is the best practice and a general "rule of thumb" recommendation to follow.

That said, I've prepared PRs that should get merged before a fix can be released:

- https://github.com/aiven/aiven-go-client/pull/333
- https://github.com/aiven/terraform-provider-aiven/pull/1651

Sorry for quite a long process on our side. I hope this information helps you to understand why changes like that might occur, too 🙂

I will be closing this issue for now, but please let me know if there are any other questions or concerns. We will try to release it ASAP, but in case there is an urgent need, you are welcome to try building the provider yourself.

In the meantime, I would recommend starting to manage the `offset_syncs_topic_location` field via Terraform.

**Comment by nickgooding** [comment] 2024-03-15 06:19
Hi, thanks for the fix.

There appears to still be an oversight with `offset_syncs_topic_location` that means the provider doesn't update the TF state based on the remote resource, so won't correctly update in the case of configuration drift. I think something like the below will fix it, but I haven't had a chance to test it thoroughly.
```diff
diff --git a/internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go b/internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
index 3bc30f73..1e5b9feb 100644
--- a/internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
+++ b/internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
@@ -213,6 +213,13 @@ func resourceMirrorMakerReplicationFlowRead(ctx context.Context, d *schema.Resou
                return diag.FromErr(err)
        }
 
+       if err := d.Set(
+               "offset_syncs_topic_location",
+               replicationFlow.ReplicationFlow.OffsetSyncsTopicLocation,
+       ); err != nil {
+               return diag.FromErr(err)
+       }
+
        return nil
 }

```

**Comment by nickgooding** [comment] 2024-03-15 09:28
>IaaC tools are designed in a way that makes them override the state of the resource if it's different from what the tool expects it to be, here's what exactly happens to the field in question:
>[...]
>- Terraform has an understanding of it as if the field wasn't set at all, because it's optional, thus it ignores the field when forging a request to our API

This is a result of the bug mentioned in my previous comment rather than an inherent limitation of Terraform. As part of generating a plan, the provider should refresh the state, detect that configuration drift has occurred, and then change the field to match configuration explicitly as part of the plan.

**Comment by Serpentiel** [comment] 2024-03-15 10:53
> > IaaC tools are designed in a way that makes them override the state of the resource if it's different from what the tool expects it to be, here's what exactly happens to the field in question:
> > [...]
> > 
> > * Terraform has an understanding of it as if the field wasn't set at all, because it's optional, thus it ignores the field when forging a request to our API
> 
> This is a result of the bug mentioned in my previous comment rather than an inherent limitation of Terraform. As part of generating a plan, the provider should refresh the state, detect that configuration drift has occurred, and then change the field to match configuration explicitly as part of the plan.

Well, yes, that's true. The problem occurred because the field was incorrectly marked as optional instead of being a required one.

Terraform doesn't shows a diff when an optional field was changed by design, because it's not tracked in the state.

https://github.com/aiven/terraform-provider-aiven/pull/1651 should change it to be a required field instead.

**Comment by nickgooding** [comment] 2024-03-15 11:49
>Terraform doesn't shows a diff, by design, when an optional field was changed externally, because it's not tracked in the state

I think you have either misunderstood my follow-up comment, which has nothing to do with the resource argument being optional, or are mistaken. There is a bug in `resourceMirrorMakerReplicationFlowRead` even accounting for the changes in your PR.

Using another optional `aiven_mirrormaker_replication_flow` to demonstrate:
1. Apply the following resource config:
```hcl
resource "aiven_mirrormaker_replication_flow" "this" {
  project        = "infrastructure-sre-sandbox"
  service_name   = "mirrormaker-sandbox"
  source_cluster = "kaluza-nonprod"
  target_cluster = "kafka-sandbox"
  enable         = true

  topics = [
    "example-topic",
  ]
  offset_syncs_topic_location = "source"
}
```
2. Deliberately introduce configuration drift
```sh
FLOW_CONFIG=$(
  curl --silent \
    --url "https://api.aiven.io/v1/project/${PROJECT_NAME}/service/${SERVICE_NAME}/mirrormaker/replication-flows/${SOURCE_CLUSTER}/${TARGET_CLUSTER}" \
    --header "Authorization: Bearer ${AIVEN_API_KEY}" \
    | jq '.replication_flow + {"offset_syncs_topic_location": "target", "topics": ["another-topic"]}  | del(.source_cluster, .target_cluster, .replication_progress)'
)
curl --request PUT \
  --url "https://api.aiven.io/v1/project/${PROJECT_NAME}/service/${SERVICE_NAME}/mirrormaker/replication-flows/${SOURCE_CLUSTER}/${TARGET_CLUSTER}" \
  --header "Authorization: Bearer ${AIVEN_API_KEY}" \
  --header 'content-type: application/json' \
  --data "${FLOW_CONFIG}"
```
3. Refresh the Terraform state. Note that `topics` has updated to reflect the configuration drift, but `offset_syncs_topic_location` has not
```
$ terraform refresh
aiven_mirrormaker_replication_flow.this: Refreshing state... [id=infrastructure-sre-sandbox/mirrormaker-sandbox/kaluza-nonprod/kafka-sandbox]
$ terraform state show aiven_mirrormaker_replication_flow.this
# aiven_mirrormaker_replication_flow.this:
resource "aiven_mirrormaker_replication_flow" "this" {
    emit_backward_heartbeats_enabled    = false
    emit_heartbeats_enabled             = false
    enable                              = true
    id                                  = "infrastructure-sre-sandbox/mirrormaker-sandbox/kaluza-nonprod/kafka-sandbox"
    offset_syncs_topic_location         = "source"
    project                             = "infrastructure-sre-sandbox"
    replication_policy_class            = "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
    service_name                        = "mirrormaker-sandbox"
    source_cluster                      = "kaluza-nonprod"
    sync_group_offsets_enabled          = false
    sync_group_offsets_interval_seconds = 1
    target_cluster                      = "kafka-sandbox"
    topics                              = [
        "another-topic",
    ]
    topics_blacklist                    = []
}
```

The result of this issue is that a `terraform apply` will not correct configuration drift in the case where only the `offset_syncs_topic_location` attribute is affected.

I am happy to go into more detail if this is still unclear.

**Comment by Serpentiel** [comment] 2024-03-15 12:03
Hey again, @nickgooding! 👋

Thank you for additional clarification. Yes, as I can see, there was a missing `d.Set` call, sorry for any confusion earlier and an oversight from my part, I though the diff that you [provided](https://github.com/aiven/terraform-provider-aiven/issues/1632#issuecomment-1999013747) was copied from my PR.

You are correct, I've updated the PR to add the missing call. I still am going to keep the field as required, because I believe it makes more sense since this value can't be empty.

Should you have any further questions or any additional information to share, please let me know 🙏

**Closed by Serpentiel** 2024-03-15 12:03 UTC
Labels: bug
