### ISSUE TITLE
Provider produces invalid plan after update to 4.x

### ISSUE THREAD

**Issue by Parnswir** [aiven/terraform-provider-aiven#1208] opened 2023-06-14 13:49 UTC
## What happened?

I'm trying to upgrade to version 4.x from 3.13.1. The [upgrade guide](https://docs.aiven.io/docs/tools/terraform/howto/upgrade-provider-v3-v4) does not apply to anything in my (humble) service definitions -- basically a single Opensearch instance + Dashboards. After the upgrade, `terraform plan` outputs a lot of errors like:

<details>
<summary>Expand to see output</summary>

```
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/aiven/aiven" planned an invalid value for
│ aiven_opensearch.default.opensearch_user_config[0].keep_index_refresh_interval:
│ planned value cty.False for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/aiven/aiven" planned an invalid value for
│ aiven_opensearch.default.opensearch_user_config[0].max_index_count: planned
│ value cty.NumberIntVal(0) for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/aiven/aiven" planned an invalid value for
│ aiven_opensearch.default.opensearch_user_config[0].opensearch_dashboards[0].max_old_space_size:
│ planned value cty.NumberIntVal(128) for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/aiven/aiven" planned an invalid value for
│ aiven_opensearch.default.opensearch_user_config[0].index_patterns[0].sorting_algorithm:
│ planned value cty.StringVal("creation_date") for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/aiven/aiven" planned an invalid value for
│ aiven_opensearch.default.opensearch_user_config[0].public_access[0].prometheus:
│ planned value cty.False for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
</details>

It looks like these are all optional or deprecated attributes. None of them is set in my terraform file:

<details>
<summary>opensearch.tf</summary>

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.69.1"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "4.69.1"
    }
    aiven = {
      source  = "aiven/aiven"
      version = ">= 4.0.0"
    }
  }
}

resource "aiven_opensearch" "default" {
  cloud_name              = var.AIVEN_CLOUD_NAME
  maintenance_window_dow  = "thursday"
  maintenance_window_time = "09:00:00"
  plan                    = "hobbyist"
  project                 = var.AIVEN_PROJECT_ID
  project_vpc_id          = aiven_project_vpc.default[0].id
  service_name            = "sample-for-github"
  static_ips              = []
  termination_protection  = false

  opensearch_user_config {
    ip_filter = [
      "0.0.0.0/0",
    ]
    index_patterns {
      max_index_count = "0"
      pattern         = "*"
    }
    opensearch_version = "2"

    opensearch_dashboards {
      enabled                    = true
      opensearch_request_timeout = 30000
    }

    public_access {
      opensearch            = "true"
      opensearch_dashboards = "true"
    }
  }

  timeouts {}
}

resource "aiven_project_vpc" "default" {
  cloud_name   = var.AIVEN_CLOUD_NAME
  network_cidr = "10.4.0.0/24"
  project      = var.AIVEN_PROJECT_ID
}

resource "aiven_gcp_vpc_peering_connection" "default" {
  gcp_project_id = local.workspace["project"]
  peer_vpc       = google_compute_network.default.name
  vpc_id         = aiven_project_vpc.default[0].id
}

resource "google_compute_network_peering" "gcp-os-peering" {
  name         = "sample-for-github"
  network      = google_compute_network.default.self_link
  peer_network = "sample-for-github"
}
```

</details>

## What did you expect to happen?

No errors after upgrade 😀

**Comment by Serpentiel** [comment] 2023-06-15 15:06
hey 👋

thanks for raising this! I will check it and will get back to you soon!

**Comment by Serpentiel** [comment] 2023-06-16 09:35
hey, @Parnswir @OlivierCookie 👋 
may I please know what Terraform version (not provider version) are you using? thank you!

**Comment by OlivierCookie** [comment] 2023-06-16 09:41
Hi @Serpentiel I use the 1.0.1 version

**Comment by Serpentiel** [comment] 2023-06-16 09:58
> Hi @Serpentiel I use the 1.0.1 version

could you please upgrade your Terraform and see if the issue is resolved then?

**Comment by OlivierCookie** [comment] 2023-06-16 12:28
Same error with terraform 1.4.6

> > Hi @Serpentiel I use the 1.0.1 version
> 
> could you please upgrade your Terraform and see if the issue is resolved then?

**Comment by Parnswir** [comment] 2023-06-16 12:36
I can confirm my errors are gone on v1.5.0. Thanks @Serpentiel!

**Comment by OlivierCookie** [comment] 2023-06-16 15:43
I asked my infra partner to upgrade terraform in version 1.5.0
I'm waiting this update to try again

**Comment by Serpentiel** [comment] 2023-06-16 16:00
@OlivierCookie thank you, please let us know here if this is still an issue with v1.5.0

**Comment by Serpentiel** [comment] 2023-06-26 13:29
I'm going to close this for now, please let us know if you have any other questions, thank you!

**Closed by Serpentiel** 2023-06-26 13:29 UTC
Labels: bug
