### ISSUE TITLE
Ordering of static_ips in state causes unnecessary changes in plan

### ISSUE THREAD

**Issue by gandelman-a** [aiven/terraform-provider-aiven#734] opened 2022-05-02 21:48 UTC
The ordering of `static_ips` on a service cause a delta in plan, resulting in unnecessary changes applied

```
  # module.postgresql.aiven_pg.default will be updated in-place
  ~ resource "aiven_pg" "default" {
        id                      = "{{redacted}}
      ~ static_ips              = [
          - "ip39153b66c63",
            "ip39153b94885",
          - "ip39153ba925d",
            "ip39153bf2cde",
          + "ip39153b66c63",
          + "ip39153ba925d",
        ]
        # (20 unchanged attributes hidden)
        # (3 unchanged blocks hidden)
    }
```

```
module.postgresql.aiven_pg.default: Still modifying... [id={{redacted}}, 10s elapsed]
module.postgresql.aiven_pg.default: Modifications complete after 19s [id={{redacted}}]
```

**Comment by mhoffm-aiven** [comment] 2022-06-02 09:32
Hey @gandelman-a ,

Did you use the `toset` function when assigning the static ips in the pg resource?

**Comment by Serpentiel** [comment] 2022-07-04 15:16
I was unable to reproduce this issue by creating a PostgreSQL database with 2 static IPs—adding 3rd static IP afterwards didn't cause it to rearrange them in any way—perhaps you forgot to use `toset` function in your Terraform configuration files

closing this now, but you're welcome to reopen it if you have anything else to add

**Closed by Serpentiel** 2022-07-04 15:16 UTC
Labels: bug

**Comment by Serpentiel** [comment] 2022-07-07 12:45
there has been another issue identified which is related to `static_ips`, please see PR #787
