### ISSUE TITLE
Aiven Cassandra resource creation takes forever

### ISSUE THREAD

**Issue by pavancse17** [aiven/terraform-provider-aiven#714] opened 2022-04-01 14:34 UTC
I have been trying to create Cassandra resource. But It is creating resource forever.
```terraform

required_providers {
    aiven = {
      source  = "aiven/aiven"
      version = "2.7.0"
    }
  }

resource "aiven_cassandra" "env" {
  project      = data.aiven_project.env.project
  cloud_name   = var.aiven_cloud_name
  plan         = var.aiven_plan
  service_name = var.resource_group

  timeouts {
    create = "120m"
  }
```

logs:
```
aiven_cassandra.env: Still creating... [1h58m1s elapsed]
aiven_cassandra.env: Still creating... [1h58m11s elapsed]
aiven_cassandra.env: Still creating... [1h58m21s elapsed]
aiven_cassandra.env: Still creating... [1h58m31s elapsed]
aiven_cassandra.env: Still creating... [1h58m41s elapsed]
aiven_cassandra.env: Still creating... [1h58m51s elapsed]
aiven_cassandra.env: Still creating... [1h59m1s elapsed]
aiven_cassandra.env: Still creating... [1h59m11s elapsed]
aiven_cassandra.env: Still creating... [1h59m21s elapsed]
aiven_cassandra.env: Still creating... [1h59m31s elapsed]
aiven_cassandra.env: Still creating... [1h59m41s elapsed]
aiven_cassandra.env: Still creating... [1h59m51s elapsed]
Error: The operation was canceled.
```

**Comment by Serpentiel** [comment] 2022-07-04 14:19
I was unable to reproduce the issue:

```log
aiven_cassandra.env: Creating...
aiven_cassandra.env: Still creating... [10s elapsed]
...
aiven_cassandra.env: Still creating... [7m30s elapsed]
aiven_cassandra.env: Creation complete after 7m31s [id=REDACTED]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

closing this now, feel free to reopen in case the issue persists or you have anything else to add

**Closed by Serpentiel** 2022-07-04 14:19 UTC
