### ISSUE TITLE
updating to 3.7.0 crashes

### ISSUE THREAD

**Issue by wanisfahmyDE** [aiven/terraform-provider-aiven#914] opened 2022-10-04 15:37 UTC
Hi there,

When upgrading from version `3.6.0` to `3.7.0` the terraform provider crashes with the following:

```
The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-aiven_v3.7.0 plugin:

panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 49 [running]:
github.com/aiven/terraform-provider-aiven/internal/schemautil.toStringSlice(...)
	github.com/aiven/terraform-provider-aiven/internal/schemautil/ipfilter.go:84
github.com/aiven/terraform-provider-aiven/internal/schemautil.NormalizeIpFilter({0xc15b00?, 0xc00086de90?}, {0xc0002886b0?, 0x1, 0x1})
	github.com/aiven/terraform-provider-aiven/internal/schemautil/ipfilter.go:28 +0xccf
github.com/aiven/terraform-provider-aiven/internal/schemautil.copyServicePropertiesFromAPIResponseToTerraform(0xc00000e900?, 0xc00023a800, {0xc00035a028?, 0xc000424480?, 0xc000394010?}, {0xc000424480, 0xe})
	github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:622 +0xba5
github.com/aiven/terraform-provider-aiven/internal/schemautil.ResourceServiceRead({0xea3628, 0xc00078e480}, 0xc000293200, {0xd05600?, 0xc0000d6b00?})
	github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:328 +0x55c
github.com/aiven/terraform-provider-aiven/internal/service/kafka.resourceKafkaRead({0xea3628, 0xc00078e480}, 0xc000293200, {0xd05600?, 0xc0000d6b00?})
	github.com/aiven/terraform-provider-aiven/internal/service/kafka/resource_kafka.go:223 +0x4b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0005947e0, {0xea3660, 0xc00079d290}, 0xd?, {0xd05600, 0xc0000d6b00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.22.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005947e0, {0xea3660, 0xc00079d290}, 0xc0007968f0, {0xd05600, 0xc0000d6b00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.22.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00052d920, {0xea3660?, 0xc00079d170?}, 0xc0006b44c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.22.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000af720, {0xea3660?, 0xc00079c900?}, 0xc00078e180)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd1b6a0?, 0xc0000af720}, {0xea3660, 0xc00079c900}, 0xc0003420e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0xea62c0, 0xc0004e09c0}, 0xc000240000, 0xc0005be000, 0x13db8b0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0xea62c0, 0xc0004e09c0}, 0xc000240000, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aiven_v3.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

the resource getting created is `aiven_kafka` 

any idea why this is happening?

Thanks

**Comment by ivan-savciuc** [comment] 2022-10-04 16:04
@wanisfahmyDE, thanks for reporting this one. What is the value for the `kafka_user_cofig.ip_filter` that this Kafka service that you are trying to create has?

**Comment by wanisfahmyDE** [comment] 2022-10-04 17:16
> 

Hi @ivan-savciuc ,

It's a couple of [ ]strings that are concatenated with concat():

 ```
kafka_user_config {

    ip_filter = concat(
      ["xx.xxx.xx.xx/32", "xx.xxx.xx.xx/32", "xx.xxx.xx.xx/32", "xx.xxx.xx.xx/32"],
      .
      .
      .
      ["yy.yyy.yy.yy/24"],
    )
}
```

**Comment by ivan-savciuc** [comment] 2022-10-05 06:34
@wanisfahmyDE, can you please provide more info for me to be able to reproduce this issue on my box? So far, I have created a Kafka service with a bunch of IP filters using `3.6.0`, and after upgrading to `3.7.0` and adding some extra IP filters, all seems to be working fine.

**Comment by wanisfahmyDE** [comment] 2022-10-06 09:13
@ivan-savciuc unfortunately I am not also able to reproduce it on my machine, but I saw the crash today again with another team using our TF module based on the aiven provider :(

I noticed in the 3.7.0 release notes that there is an entry:
"static_ips schema type change from list to set" 
can this be related? a snippet of our usage looks like this:

```
resource "aiven_static_ip" "static_ips" {
  project    = local.project
  cloud_name = local.aiven_default_cloud
  count      = var.num_of_static_ips
}
```

```
resource "aiven_kafka" "aiven_kafka" {
  project                 = local.project
  cloud_name              = local.aiven_default_cloud
  plan                    = var.cluster_plan
  disk_space              = var.disk_space
  service_name            = var.cluster_name
  project_vpc_id          = data.aiven_project_vpc.vpc.id
  maintenance_window_dow  = var.maintenance_window_dow
  maintenance_window_time = var.maintenance_window_time
  default_acl             = false
  termination_protection  = var.cluster_termination_protection_enabled
  karapace                = var.kafka_rest_enabled == true || var.schema_registry_enabled == true ? true : false
  static_ips              = var.static_ips_enabled ? aiven_static_ip.static_ips.*.static_ip_address_id : null
  kafka_user_config {
    static_ips = var.static_ips_enabled ? true : null

  ip_filter = concat(
     ["xx.xxx.xx.xx/32", "xx.xxx.xx.xx/32", "xx.xxx.xx.xx/32", "xx.xxx.xx.xx/32"],
     .
     .
     .
     ["yy.yyy.yy.yy/24"],
   )

    schema_registry = var.schema_registry_enabled ? "true" : "false"
    kafka_rest      = var.kafka_rest_enabled ? "true" : "false"

    kafka_authentication_methods {
      certificate = true
      sasl        = true
    }

    kafka {
      auto_create_topics_enable                                  = lookup(var.kafka_broker_settings, "auto_create_topics_enable", null)
      compression_type                                           = lookup(var.kafka_broker_settings, "compression_type", null)
      connections_max_idle_ms                                    = lookup(var.kafka_broker_settings, "connections_max_idle_ms", null)
      default_replication_factor                                 = lookup(var.kafka_broker_settings, "default_replication_factor", null)
      group_initial_rebalance_delay_ms                           = lookup(var.kafka_broker_settings, "group_initial_rebalance_delay_ms", null)
      group_max_session_timeout_ms                               = lookup(var.kafka_broker_settings, "group_max_session_timeout_ms", null)
      group_min_session_timeout_ms                               = lookup(var.kafka_broker_settings, "group_min_session_timeout_ms", null)
      log_cleaner_delete_retention_ms                            = lookup(var.kafka_broker_settings, "log_cleaner_delete_retention_ms", null)
      log_cleaner_max_compaction_lag_ms                          = lookup(var.kafka_broker_settings, "log_cleaner_max_compaction_lag_ms", null)
      log_cleaner_min_cleanable_ratio                            = lookup(var.kafka_broker_settings, "log_cleaner_min_cleanable_ratio", null)
      log_cleaner_min_compaction_lag_ms                          = lookup(var.kafka_broker_settings, "log_cleaner_min_compaction_lag_ms", null)
      log_cleanup_policy                                         = lookup(var.kafka_broker_settings, "log_cleanup_policy", null)
      log_flush_interval_messages                                = lookup(var.kafka_broker_settings, "log_flush_interval_messages", null)
      log_flush_interval_ms                                      = lookup(var.kafka_broker_settings, "log_flush_interval_ms", null)
      log_index_interval_bytes                                   = lookup(var.kafka_broker_settings, "log_index_interval_bytes", null)
      log_index_size_max_bytes                                   = lookup(var.kafka_broker_settings, "log_index_size_max_bytes", null)
      log_message_downconversion_enable                          = lookup(var.kafka_broker_settings, "log_message_downconversion_enable", null)
      log_message_timestamp_difference_max_ms                    = lookup(var.kafka_broker_settings, "log_message_timestamp_difference_max_ms", null)
      log_message_timestamp_type                                 = lookup(var.kafka_broker_settings, "log_message_timestamp_type", null)
      log_preallocate                                            = lookup(var.kafka_broker_settings, "log_preallocate", null)
      log_retention_bytes                                        = lookup(var.kafka_broker_settings, "log_retention_bytes", null)
      log_retention_hours                                        = lookup(var.kafka_broker_settings, "log_retention_hours", null)
      log_retention_ms                                           = lookup(var.kafka_broker_settings, "log_retention_ms", null)
      log_roll_jitter_ms                                         = lookup(var.kafka_broker_settings, "log_roll_jitter_ms", null)
      log_roll_ms                                                = lookup(var.kafka_broker_settings, "log_roll_ms", null)
      log_segment_bytes                                          = lookup(var.kafka_broker_settings, "log_segment_bytes", null)
      log_segment_delete_delay_ms                                = lookup(var.kafka_broker_settings, "log_segment_delete_delay_ms", null)
      max_connections_per_ip                                     = lookup(var.kafka_broker_settings, "max_connections_per_ip", null)
      max_incremental_fetch_session_cache_slots                  = lookup(var.kafka_broker_settings, "max_incremental_fetch_session_cache_slots", null)
      message_max_bytes                                          = lookup(var.kafka_broker_settings, "message_max_bytes", null)
      min_insync_replicas                                        = lookup(var.kafka_broker_settings, "min_insync_replicas", null)
      num_partitions                                             = lookup(var.kafka_broker_settings, "num_partitions", null)
      offsets_retention_minutes                                  = lookup(var.kafka_broker_settings, "offsets_retention_minutes", null)
      producer_purgatory_purge_interval_requests                 = lookup(var.kafka_broker_settings, "producer_purgatory_purge_interval_requests", null)
      replica_fetch_max_bytes                                    = lookup(var.kafka_broker_settings, "replica_fetch_max_bytes", null)
      replica_fetch_response_max_bytes                           = lookup(var.kafka_broker_settings, "replica_fetch_response_max_bytes", null)
      socket_request_max_bytes                                   = lookup(var.kafka_broker_settings, "socket_request_max_bytes", null)
      transaction_remove_expired_transaction_cleanup_interval_ms = lookup(var.kafka_broker_settings, "transaction_remove_expired_transaction_cleanup_interval_ms", null)
      transaction_state_log_segment_bytes                        = lookup(var.kafka_broker_settings, "transaction_state_log_segment_bytes", null)
    }

    public_access {
      kafka           = var.kafka_cluster_public_access_enabled
      prometheus      = var.prometheus_public_access_enabled
      kafka_rest      = var.kafka_rest_public_access_enabled
      schema_registry = var.schema_registry_public_access_enabled
    }
  }
}

```

**Comment by Serpentiel** [comment] 2022-10-06 11:06
hey 👋 
thanks for bringing this to our attention!

this might be a duplicate of #909 

we will be performing an investigation now to see what could be done about it and how to reproduce it

**Comment by Serpentiel** [comment] 2022-10-17 08:50
duplicate of #909, please watch for it from now on

**Closed by Serpentiel** 2022-10-17 08:50 UTC
Labels: duplicate
