### ISSUE TITLE
error authorizing query: avnadmin 

### ISSUE THREAD

**Issue by YingwenX** [aiven/terraform-provider-aiven#1467] opened 2023-12-06 10:00 UTC
## What can we help you with?

error authorizing query: avnadmin not authorized to exe ││ cute statement 'CREATE DATABASE bci_esw_nexeed_perf32_cm', requires admin privilege\\\"}\\

## Where would you expect to find this information?

avnadmin should have privilege permission to create db, but somehow the default user for service: avnadmin face the permission issue

**Comment by byashimov** [comment] 2023-12-08 08:56
Hey. Could you please share a bit more?
What was your tf file when you got this? Thanks.

**Comment by YingwenX** [comment] 2023-12-11 09:53
[](url)i'm sorry because the tf code are project restrict and i can't share the whole scripts here, but somehow the svc can be created as well as the defaultdb, but will receive api error, and the influxdb would get taint
![Uploading influx_svc_taint.PNG…]()

**Comment by Serpentiel** [comment] 2023-12-11 09:55
Hey, @YingwenX! 👋 

Looks like the picture that you have uploaded is broken, could you please upload it again?

Thank you!

**Comment by YingwenX** [comment] 2023-12-11 09:56
the currect solution is untaint and refresh resource, that will work, but don't get why it happened, when we test from vm directly it will work, the error only occurres when using Azure storage account to store resource state

**Comment by YingwenX** [comment] 2023-12-11 09:57
![Uploading influx_svc_taint.PNG…]()

**Comment by YingwenX** [comment] 2023-12-11 09:58
seems the images loaded failed again, i'll past in text: 
terraform state show module.skeleton.module.influx[0].
aiven_influxdb.this
# module.skeleton.module.influx[0].aiven_influxdb.this: (tainted)
resource "aiven_influxdb" "this" {
    cloud_name              = "azure-westeurope"
    disk_space_cap          = "0B"
    disk_space_default      = "16GiB"
    disk_space_step         = "0B"
    disk_space_used         = "16GiB"
    id                      = "***"
    influxdb                = []
    maintenance_window_dow  = "tuesday"
    maintenance_window_time = "01:30:00"
    plan                    = "startup-4"
    project                 = "***"
    service_name            = "influx-**"
    service_type            = "influxdb"
    service_uri             = (sensitive value)
    state                   = "RUNNING"
    termination_protection  = false

    influxdb_user_config {
        ip_filter_string = []
    }
}

**Comment by Serpentiel** [comment] 2024-01-10 11:23
Hey, @YingwenX! 👋 

Sorry for taking quite a while to get back to you, it was due to holidays and other urgent matters.

I'm having trouble reproducing this, would you mind sharing step-by-step reproduction scenario with a completely new and unrelated Terraform project?

This could simply be a manifest file which is possible to run without any additional setup required.

Thank you!

**Comment by Serpentiel** [comment] 2024-03-26 10:25
Hey, @YingwenX! 👋

Since there hasn't been an update to this ticket, I will close it for the time being.

Feel free to reopen it if you have any additional information to share.

**Closed by Serpentiel** 2024-03-26 10:25 UTC
Labels: bug, needs info
