### ISSUE TITLE
Unable to update aiven_service_integration_endpoint of endpoint type `rsyslog`

### ISSUE THREAD

**Issue by yjwong** [aiven/terraform-provider-aiven#1028] opened 2023-01-03 16:25 UTC
## What happened?

I was trying to update `rsyslog_user_config` with a new cert and key. The plan succeeded but the apply failed. This worked in version 3.5.1 but fails after upgrading to 3.10.0. 

The error was:
```
Error: 400: {"errors":[{"message":"Invalid 'user_config': Invalid input: 'server' is a required property","status":400}],"message":"Invalid 'user_config': Invalid input: 'server' is a required property"}
```

Our Terraform file looks like:

```terraform
resource "aiven_service_integration_endpoint" "production_logstash" {
  project = "glints"

  endpoint_type = "rsyslog"
  endpoint_name = "logstash"

  rsyslog_user_config {
    format = "rfc3164"
    port   = "<snip>"
    server = "<snip>"
    tls    = "true"

    ca = chomp(<<EOT
...
EOT
    )

    cert = chomp(<<EOT
...
EOT
    )

    key = var.aiven_service_integration_endpoint_production_logstash_key
  }
}
```

## What did you expect to happen?

I expect the changes to the cert to be applied correctly like in 3.5.1.

**Comment by byashimov** [comment] 2023-01-09 12:46
Hi @yjwong!
"server" field is indeed required, but I see it is already is in your manifest. Had you had it when you got that error or added later?
I have just tried this and it works well.

**Comment by oleewere** [comment] 2023-01-10 22:39
i have faced similar issue with using 3.10.0 but for opensearch retention index patterns:
```
{"errors":[{"message":"Invalid 'user_config': Invalid input for index_patterns: 'pattern' is a required property","status":400}],"message":"Invalid 'user_config': Invalid input for index_patterns: 'pattern' is a required property"} - 
```
but all the pattern fields were filled, even in the error state ...using earlier version like 3.5.1 helped me as well

**Comment by byashimov** [comment] 2023-01-11 16:25
Hey @oleewere !
Could you share your user config state please?
I can't reproduce it ether :(

**Comment by byashimov** [comment] 2023-01-12 10:24
Hi @yjwong @oleewere 
Turns out it's been fixed in v3.11.0. Please upgrade to the latest version.

**Comment by abmateen** [comment] 2023-02-23 17:16
@byashimov 
We tried applying changes to our "rsyslog" service integration and used provider version 3.11.0, 3.12.0, 3.12.1 with same error i.e : 

`Error: 400: {"errors":[{"message":"Invalid 'user_config': Invalid input: 'server' is a required property","status":400}],"message":"Invalid 'user_config': Invalid input: 'server' is a required property"}
`
But when using v3.5.1 it went through just fine.

**Comment by Serpentiel** [comment] 2023-05-02 12:30
looks like this and #1142 are duplicates, let's stick to #1142 to discuss this

**Closed by Serpentiel** 2023-05-02 12:30 UTC
Labels: bug
