### ISSUE TITLE
Errors and timeouts with v2.0.8

### ISSUE THREAD

**Issue by harshal-shah** [aiven/terraform-provider-aiven#343] opened 2020-10-22 14:31 UTC
Hi, 
After we started using the provider version 2.0.8, our terraform workflow started giving errors such as below: 
~~~
Error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)
Error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)
~~~

Refreshing resource to state would generally finish in a minute but took 45 minutes before being timed out. 
While running terraform in debug mode we found multiple events such as 
~~~
2020/10/22 15:32:16 [TRACE] dag/walk: vertex "aiven_kafka_acl.dph-imjustapoortboynobodylovesme-deleterequest-read (expand)" is waiting for "aiven_kafka_topic.rawevents_heisjustapoorboyfromapoorfamily-requested (expand)"
2020/10/22 15:32:16 [TRACE] dag/walk: vertex "aiven_kafka_acl.sparehimhislifefromthismonstrosity-readwrite (expand)" is waiting for "aiven_kafka_topic.easycomeeasygowillyouletmego_response (expand)"
2020/10/22 15:32:16 [TRACE] dag/walk: vertex "aiven_kafka_acl.bismillahnowewillnotletyougo-response (expand)" is waiting for "aiven_kafka_topic.rawevents_mamamiamamamialetmego-response (expand)"
~~~

These problems did not happen when using provider version 2.0.7 so we are pinning our automation to use 2.0.7 to mitigate this.

**Comment by ivan-savciuc** [comment] 2020-10-23 08:14
Hi, can you please share some of the specifics of your set up, for us to be able to reproduce this? It looks like this issue is related to the new caching layer that is using a different Aiven API endpoint to get topics and topic configuration.

**Comment by harshal-shah** [comment] 2020-10-23 08:47
hi @ivan-savciuc 
Please let us know what details would you like from us.
We're using terraform version 0.13.3
our kafka version is 2.4

**Comment by harshal-shah** [comment] 2020-10-23 08:48
Adding @juniorz to this conversation to provide details in case of my absence.

**Comment by ivan-savciuc** [comment] 2020-10-23 09:53
Thank you for your input @harshal-shah, I was able to reproduce it if to put some stress on caching layer, created PR with a fix, and we will release it ASAP when merged.

**Comment by harshal-shah** [comment] 2020-10-23 09:58
Awesome, please let us know once you release, we'd be happy to test it.

**Closed** 2020-10-23 10:03 UTC
Labels: bug
