### ISSUE TITLE
Cannot create additional Azure Privatelink

### ISSUE THREAD

**Issue by leandrorosa** [aiven/terraform-provider-aiven#1274] opened 2023-07-26 13:57 UTC
## What happened?

While trying to setup an additional Azure PrivateLink connection for a service an error was triggered during the connection approval :
```hcl
Error: number of privatelink connections != 1 (2

  with module.aiven_redis_privatelink.aiven_azure_privatelink_connection_approval.approval,
  on network/aiven_privatelink/main.tf line 28, in resource "aiven_azure_privatelink_connection_approval" "approval":
  28: resource "aiven_azure_privatelink_connection_approval" "approval" {
```

 

## What did you expect to happen?

I would expect the creation of the additional Azure Privatelink

## What else do we need to know?

I could overcome this using the Aiven Cli with:
```shell
avn service privatelink azure connection approve
avn service privatelink azure connection update
```

**Comment by Serpentiel** [comment] 2023-07-26 14:01
hey, @leandrorosa! 👋
thank you for raising this issue, I'm going to check this now!

**Comment by Serpentiel** [comment] 2023-07-26 14:20
hey again @leandrorosa! 👋
I have created a PR to add this feature, it will be released soon, but in case of urgency, you are welcome to build the provider manually!

**Comment by leandrorosa** [comment] 2023-07-26 14:28
Wow, that was fast! 

No worries, I will wait for the next release.

Many thanks @Serpentiel!

**Comment by Serpentiel** [comment] 2023-07-27 12:34
hey, @leandrorosa! 👋

after performing additional QA evaluation, we have noticed that Aiven public API currently does not supports multiple Privatelink connections to a single service

may we know exactly (step-by-step) how you create these?

we have tried to reproduce it with your provided description, however for us it results in the following error:

```log
aiven_azure_privatelink.c1: Creation complete after 36s [id=aiven-ci-terraform-provider/ivans-pg2]
╷
│ Error: 409: {"errors":[{"message":"Service already has Privatelink configured","status":409}],"message":"Service already has Privatelink configured"} - 
│ 
│   with aiven_azure_privatelink.c2,
│   on getting-started.tf line 50, in resource "aiven_azure_privatelink" "c2":
│   50: resource "aiven_azure_privatelink" "c2" {
│ 
╵
```

**Comment by Serpentiel** [comment] 2023-08-03 10:27
hey, @leandrorosa! 👋

since it's been a week, and we haven't heard back from you, I'm going to close this for now

we were unable to confirm that this is supported by Aiven API, and is supported in general, and therefore cannot merge the PR

please let us know if you have a way to reproduce it, so that the service ends up having multiple Privatelink configured

**Closed by Serpentiel** 2023-08-03 10:27 UTC
Labels: enhancement
