### ISSUE TITLE
Aiven Team Resource seems to use wrong reference

### ISSUE THREAD

**Issue by phumberdroz** [aiven/terraform-provider-aiven#267] opened 2020-08-03 15:42 UTC
I have a team project resource like this:

```hcl
resource "aiven_account_team_project" "members" {
  account_id   = data.aiven_account.spectrm.account_id
  team_id      = data.aiven_account_team.members.team_id
  project_name = aiven_project.stage.project
  team_type    = "read_only"
}
```
I am using terraform workspaces which results in creating 6 of these in total (members and owners)

```
  # aiven_account_team_project.members will be updated in-place
  ~ resource "aiven_account_team_project" "members" {
        account_id   = "a2cbbc614974"
        id           = "a2cbbc614974/at2cbbc9bc9c1/spectrm-staging-qjvr47jo"
      ~ project_name = "spectrm-development-2f8y79lm" -> "spectrm-staging-qjvr47jo"
        team_id      = "at2cbbc9bc9c1"
        team_type    = "read_only"
    }
  # aiven_account_team_project.owners will be updated in-place
  ~ resource "aiven_account_team_project" "owners" {
        account_id   = "a2cbbc614974"
        id           = "a2cbbc614974/at2cbbc6b5d90/spectrm-staging-qjvr47jo"
      ~ project_name = "spectrm-development-2f8y79lm" -> "spectrm-staging-qjvr47jo"
        team_id      = "at2cbbc6b5d90"
        team_type    = "admin"
    }
```

And with the next applies it always wants to change the projects names.

**Comment by ivan-savciuc** [comment] 2020-08-04 12:04
Can you please run the following command `terraform state show 'aiven_project.stage'` and provide a project name value? So we can better understand what is happening on your end?

**Comment by phumberdroz** [comment] 2020-08-04 13:46
```
# aiven_project.stage:
resource "aiven_project" "stage" {
    account_id        = "a2cbbc614974"
    billing_address   = <<~EOT
        xxxxxxx
    EOT
    billing_emails    = [
        "xxxx@xxxxx.io",
    ]
    ca_cert           = <<~EOT
        -----BEGIN CERTIFICATE-----
        xxxxxxxx
        -----END CERTIFICATE-----
    EOT
    card_id           = "xxxxxxxxx"
    copy_from_project = "spectrm-xxxx"
    country_code      = "DE"
    id                = "spectrm-development-2f8y79lm"
    project           = "spectrm-development-2f8y79lm"
    technical_emails  = [
        "xxx@xxxx.io",
    ]
}
```

This is for my dev env

**Comment by ivan-savciuc** [comment] 2020-08-04 14:40
Thanks for providing this info. 
It looks like there is a problem in TF workspace state file, it has a different project name in comparison with Aiven API. It is unlikely a bug in Aiven Terraform Provider since Terraform itself manages references between resources and provider only performs resource CRUD operations with the given input data.

As an immediate solution, I would recommend running `terraform refresh`, thought it might be tricky if you are not using the latest TF version because of this issue https://github.com/hashicorp/terraform/pull/22885. Or deleting a state file from a workspace and `terraform import` all the necessary resources. 

I cannot reproduce it by running https://github.com/aiven/terraform-provider-aiven/tree/master/examples/account using `v1.3.2` in various workspaces. 

I do have a couple of more questions to understand what is happening:
- When you are running `terraform apply` it generates plans which want to update all the related  `aiven_account_team_project` resources but NOT `aiven_project.stage`? 
- Is this happening only when you switch to your development workspace in Terraform but all works well in `default` workspace?

**Comment by phumberdroz** [comment] 2020-08-04 18:33
here is a test case to reproduce it:
https://github.com/phumberdroz/aiven-terraform-provider-bug

**Comment by phumberdroz** [comment] 2020-08-05 11:00
@ivan-savciuc does this help you reproduce and make a fix?

**Comment by ivan-savciuc** [comment] 2020-08-05 11:23
@phumberdroz thanks for taking your time and providing the TF code to debug this issue, I'm running https://github.com/phumberdroz/aiven-terraform-provider-bug `test.sh` and yes I can reproduce the same issue, and right now looking for a solution.

**Comment by ivan-savciuc** [comment] 2020-08-05 14:22
Thanks again for the test case, it helped to narrow down the problem, created PR with the fix https://github.com/aiven/terraform-provider-aiven/pull/268, and we will release ASAP when it is merged.

**Comment by phumberdroz** [comment] 2020-08-05 14:24
Cool ! Thanks for the quick turn around! I actually was looking at those lines yesterday but it looked fine to my eyes.

**Closed** 2020-08-06 11:18 UTC
Labels: bug
